spring.application.name=Menedzer Amatorskiej Ligi SimRacingowej
# Baza H2 w pamięci
spring.datasource.url=jdbc:h2:mem:simracingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate automatycznie stworzy tabele na podstawie klas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Włączenie konsoli H2 pod adresem http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# limit wielkości plików
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

